#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : usbutils
Version  : 012
Release  : 18
URL      : https://www.kernel.org/pub/linux/utils/usb/usbutils/usbutils-012.tar.xz
Source0  : https://www.kernel.org/pub/linux/utils/usb/usbutils/usbutils-012.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0+
Requires: usbutils-bin = %{version}-%{release}
Requires: usbutils-man = %{version}-%{release}
BuildRequires : clr-hardware-files
BuildRequires : pkgconfig(libudev)
BuildRequires : pkgconfig(libusb-1.0)

%description
<!---
SPDX-License-Identifier: GPL-2.0+
-->
# usbutils
This is a collection of USB tools for use on Linux and BSD systems to
query what type of USB devices are connected to the system.  This is to
be run on a USB host (i.e. a machine you plug USB devices into), not on
a USB device (i.e. a device you plug into a USB host.)

%package bin
Summary: bin components for the usbutils package.
Group: Binaries

%description bin
bin components for the usbutils package.


%package man
Summary: man components for the usbutils package.
Group: Default

%description man
man components for the usbutils package.


%prep
%setup -q -n usbutils-012
cd %{_builddir}/usbutils-012

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1572556894
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%autogen --disable-static --datadir=/usr/share/hwdata
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1572556894
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/lsusb
/usr/bin/lsusb.py
/usr/bin/usb-devices
/usr/bin/usbhid-dump

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/usb-devices.1
/usr/share/man/man8/lsusb.8
/usr/share/man/man8/usbhid-dump.8
