#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v13
# autospec commit: dc0ff31
#
Name     : usbutils
Version  : 017
Release  : 23
URL      : https://mirrors.kernel.org/pub/linux/utils/usb/usbutils/usbutils-017.tar.gz
Source0  : https://mirrors.kernel.org/pub/linux/utils/usb/usbutils/usbutils-017.tar.gz
Summary  : usbutils    This is a collection of USB tools for use on Linux and BSD systems\
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+ GPL-3.0
Requires: usbutils-bin = %{version}-%{release}
Requires: usbutils-license = %{version}-%{release}
Requires: usbutils-man = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : clr-hardware-files
BuildRequires : pkgconfig(libudev)
BuildRequires : pkgconfig(libusb-1.0)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
<!---
SPDX-License-Identifier: GPL-2.0-or-later
-->
# usbutils
This is a collection of USB tools for use on Linux and BSD systems to
query what type of USB devices are connected to the system.  This is to
be run on a USB host (i.e. a machine you plug USB devices into), not on
a USB device (i.e. a device you plug into a USB host.)

%package bin
Summary: bin components for the usbutils package.
Group: Binaries
Requires: usbutils-license = %{version}-%{release}

%description bin
bin components for the usbutils package.


%package dev
Summary: dev components for the usbutils package.
Group: Development
Requires: usbutils-bin = %{version}-%{release}
Provides: usbutils-devel = %{version}-%{release}
Requires: usbutils = %{version}-%{release}

%description dev
dev components for the usbutils package.


%package extras
Summary: extras components for the usbutils package.
Group: Default

%description extras
extras components for the usbutils package.


%package license
Summary: license components for the usbutils package.
Group: Default

%description license
license components for the usbutils package.


%package man
Summary: man components for the usbutils package.
Group: Default

%description man
man components for the usbutils package.


%prep
%setup -q -n usbutils-017
cd %{_builddir}/usbutils-017
pushd ..
cp -a usbutils-017 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1720019473
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static --datadir=/usr/share/hwdata
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static --datadir=/usr/share/hwdata
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1720019473
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/usbutils
cp %{_builddir}/usbutils-%{version}/LICENSES/GPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/usbutils/55ecbe8d9853ba75e3ce95a3a60f70bb728d51ac || :
cp %{_builddir}/usbutils-%{version}/LICENSES/GPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/usbutils/c0a595d97337dfa9f56fc0f71fbd8013b1d4cb27 || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/lsusb
/V3/usr/bin/usbhid-dump
/usr/bin/lsusb
/usr/bin/usb-devices
/usr/bin/usbhid-dump

%files dev
%defattr(-,root,root,-)
/usr/lib64/pkgconfig/usbutils.pc

%files extras
%defattr(-,root,root,-)
/usr/bin/lsusb.py

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/usbutils/55ecbe8d9853ba75e3ce95a3a60f70bb728d51ac
/usr/share/package-licenses/usbutils/c0a595d97337dfa9f56fc0f71fbd8013b1d4cb27

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/usb-devices.1
/usr/share/man/man8/lsusb.8
/usr/share/man/man8/usbhid-dump.8
