#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : usbutils
Version  : 008
Release  : 8
URL      : https://www.kernel.org/pub/linux/utils/usb/usbutils/usbutils-008.tar.xz
Source0  : https://www.kernel.org/pub/linux/utils/usb/usbutils/usbutils-008.tar.xz
Summary  : USB device database
Group    : Development/Tools
License  : GPL-2.0+ GPL-2.0
Requires: usbutils-bin
Requires: usbutils-doc
BuildRequires : pkgconfig(libudev)
BuildRequires : pkgconfig(libusb-1.0)

%description
first get usbhid-dump:
git submodule init
git submodule update
initialize autobuild with:
autoreconf --install --symlink
configure with:
./configure
build with:
make

%package bin
Summary: bin components for the usbutils package.
Group: Binaries

%description bin
bin components for the usbutils package.


%package dev
Summary: dev components for the usbutils package.
Group: Development
Requires: usbutils-bin

%description dev
dev components for the usbutils package.


%package doc
Summary: doc components for the usbutils package.
Group: Documentation

%description doc
doc components for the usbutils package.


%prep
%setup -q -n usbutils-008

%build
%configure --disable-static
make V=1 %{?_smp_mflags}

%check
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/lsusb
/usr/bin/lsusb.py
/usr/bin/usb-devices
/usr/bin/usbhid-dump

%files dev
%defattr(-,root,root,-)
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
%doc /usr/share/man/man8/*
